name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Build
        run: npm run build

      - name: Create worktree and copy files
        run: |
          git fetch origin gh-pages
          git worktree add ../pb gh-pages
          rm -r ../pb/*
          cp -a src/dist/. ../pb/

      - name: Setup credentials
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          global: true
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Commit
        working-directory: ../pb/
        run: |
          git add .
          git commit --amend -m "Update" --author="Github Action <github-action@users.noreply.github.com>"
          git push --force
